config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  devise_for :users
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :sales
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categories
  belongs_to :suppliers
  has_many :warehouse_records
end

app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products
	has_many :warehouse_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categorias = Category.all
  end

  def new
    @categoria = Category.new
  end

  def edit
  end

  def create
    @categoria = Category.new(category_params)

    respond_to do |format|
      if @categoria.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @categoria.update(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @categoria.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private 
    def set_category
      @categoria = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:nombre, :descripcion)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @categoria, remote: true do |f| %>
    <div class="form-group">
      <h4 class="control-label">Datos de la categoría:</h4>
    </div>

    <div class="item form-group<%= @categoria.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :nombre, "Nombre de Categoría: " %>
      <div class="input-group">
        <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre de la categoría..."} %>        
        <%if @categoria.errors[:nombre].any? %>
          <p class="bg-danger"><%= @categoria.errors[:nombre].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @categoria.errors[:descripcion].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :descripcion, "Descripción de la categoría: " %>
      <div class="input-group">
        <%= f.text_area :descripcion, {class: "form-control", :placeholder=>"Introduzca la descripción de la categoría..."} %>
        <%if @categoria.errors[:descripcion].any? %>
          <p class="bg-danger"><%= @categoria.errors[:descripcion].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
      <%= f.submit @categoria.new_record? ? "Crear Categoría" : "Actualizar Categoría", :class => "btn btn-success"%>
    </div>  
<% end %>

app/views/categories/_modal_categorias.html.erb
<!-- Modal -->
<div class="modal fade" id="modalCategorias" tabindex="-1" role="dialog" aria-labelledby="modalCategoriasLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-categorias-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-categorias modal-body" id="modal-body-categorias">
         
      </div>
      <div class="modal-footer" id="modal-footer-categorias">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/create.js.erb
  
$('#modalCategorias').modal('toggle');
$('#tablaCategorias').append(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/categories/destroy.js.erb
$('#categoria_<%= @categoria.id %>').fadeOut();

app/views/categories/edit.js.erb
$('#modal-categorias-title').html("Editar categoria");

$('.modal-body-categorias').html('<%= j render("form") %>');
 
$('#modalCategorias').modal("show");

app/views/categories/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categorias de productos</h1>

<div>  
  <%= link_to new_category_path, {remote: true, class: "btn btn-info", id: "anadir-categoria-btn"}  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
</div>
<br />

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
       <table id="tablaCategorias" class="table table-bordered" width="100%">
         <thead>
           <tr>
             <th>Nombre Categoría</th>
             <th>Descripcion</th>
             <th></th>
           </tr>
         </thead>
         <tbody>
         <% @categorias.each do |cat| %>
            <tr id="categoria_<%= cat.id %>" >
                <td><%= cat.nombre %></td>
                <td><%= cat.descripcion %></td>
                <td>
                <%= link_to "editar", edit_category_path(cat), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                <%= link_to 'Borrar', cat, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{cat.nombre}?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
         <% end %>
         </tbody>
       </table>
    </div>
  </div>
</div>

<div class="container">
  <h2>Modal Example</h2>
  <!-- Button to Open the Modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Open modal
  </button>

  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Modal Heading</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          Modal body..
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
  
</div>
<%= render 'modal_categorias' %>

app/views/categories/new.js.erb
// Add the dialog title
$('#modal-categorias-title').html("Nueva categoria");
 
// Render the new form
$('.modal-body-categorias').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#modalCategorias').modal("show");

app/views/categories/update.js.erb
$('#modalCategorias').modal('toggle');
$('#categoria_<%= @categoria.id %>').replaceWith(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>